repos:
  - repo: local
    hooks:
      - id: format-files
        name: Format files
        entry: uv tool run black
        language: unsupported
        types: [python]
      - id: update-requirements-txt
        name: Update requirements.txt
        entry: uv export --no-hashes --no-annotate --no-dev --format requirements.txt --output-file requirements.txt
        language: unsupported
        pass_filenames: false
