[project]
name = "lihkg-scraper"
version = "2026"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4==4.14.3",
    "requests==2.32.5",
    "selenium==4.39.0",
]

[tool.uv]
exclude-newer = "30 days"
