[project]
name = "lihkg-scraper"
version = "2026.2"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4==4.14.3",
    "requests==2.32.5",
    "selenium==4.39.0",
]

[dependency-groups]
dev = [
    "pre-commit==4.5.1",
]
